[package]
name = "chat_plus_plus"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", features = ["full"] }
tokio-tungstenite = "*"
futures = "0.3.31"
log = "0.4.28"
env_logger = "0.11.8"
